### ISSUE TITLE
Error: Something went wrong during file copy where not all bytes were written!

### ISSUE THREAD

**Issue by Alwayshelping** [dumpling-app/dumpling#1]
i was trying to dump my wii u online files to cemu. but then i got this error. i dont know if its my wii u or a bug

**Comment by Crementif** [comment]
Hey,

Were you the same person who I helped in the Cemu discord by any chance? I don't recall if you had your issue resolved. Thanks for filing your issue though!

First of all, some stuff you could try is:
1). Try the new Dumpling version that I just released. Might not be released in the app store yet so you might have to use the manual method from [here](https://github.com/emiyl/dumpling/tree/2.0#how-to-install) (see method 2).
2). Make sure that your SD card isn't set to locked. Maybe you even have to make a backup of the files on there, reformat it and then put the files back. Then try Dumpling again. The error you got usually indicates something wrong with the SD card.

**Comment by Crementif** [comment]
Gonna close this issue due to lack of reproducibility and staleness.

**Comment by Kat-09** [comment]
I got this issue and then my usb became read only, it was not read only before and I am unable to change it back pls help lmao
My Usb does not have a write only switch btw
