### ISSUE TITLE
Dumpling resets instead of dumps?

### ISSUE THREAD

**Issue by JarieSuisen** [dumpling-app/dumpling#12]
So, I've successfully dumped 2 digital games (Smash Bros. WiiU and Xenoblade X) and one digital game (Wii Fit U). Each of them went by just fine. But now I'm trying to dump the disc of Zero-Nuregarasu no Miko and I can get to the step where I choose to either check the files sizes then dump or to just dump, no matter which one I pick it just reverts back to the main Dumpling menu. I've restarted several times and can't figure it out.

I dunno if it matters, but all my games are Japanese. But as I said, three successes already.

**Comment by bauspanderu** [comment]
Happens to me too with Super Mario Maker, European version. I tried with Mariokart 8, and it did this the first time too, but the second time, it worked...

Edit: when i try the second time with Mario Maker, it opens a log saying that it couldn't find a required .xml file.

**Comment by Crementif** [comment]
The starting of disc dumping should be a lot more stable in the new version I just released since we changed a lot of stuff underneath the hood. See https://github.com/emiyl/dumpling/releases/tag/2.2.1.

**Comment by Crementif** [comment]
Gonna close this issue since stability has been improved quite a bit in recent versions, specifically for disc dumping.
