### ISSUE TITLE
Dumpling doesn't recognize USB

### ISSUE THREAD

**Issue by NebulaDusk** [dumpling-app/dumpling#13]
So I've done about everything I can think of. I have a SanDisk 3.0 USB, 32GB and completely formatted, tried with both wiiu and windows formatting, choosing different slots on the system, keeping it plugged in or pulling it out and plugging it back in, tried using a different SanDisk USB drive as well that wasn't 3.0, and no results. It is definitely a FAT32 file system with only 1 partition, and about 28.6GB useable.

**Comment by CJK95** [comment]
Usb drive controllers are fickle, especially with FAT32.  You may find one
that works, but even those tend to corrupt.   Pickup an external hdd along
with a dual USB adapter and plug both ends into the front ports.

**Comment by SMarioMan** [comment]
I am having a similar issue, but with an external HDD. It uses the dual USB adapter and is formatted with the FAT32 filesystem. It is recognized with no issues by [wudump](https://github.com/FIX94/wudump), but Dumpling doesn't detect it.

**Comment by NebulaDusk** [comment]
What I ended up doing was just buying a new SD card, a 32GB was like $10USD so super cheap, and it was enough to move both the dlc and main game files over with plenty of space left. I had gone through all my other options at that point, honestly. But it's probably the best solution.

**Comment by cvlver** [comment]
> So I've done about everything I can think of. I have a SanDisk 3.0 USB, 32GB and completely formatted, tried with both wiiu and windows formatting, choosing different slots on the system, keeping it plugged in or pulling it out and plugging it back in, tried using a different SanDisk USB drive as well that wasn't 3.0, and no results. It is definitely a FAT32 file system with only 1 partition, and about 28.6GB useable.

Same for me, mine is a SanDisk Cruzer Glide USB Device & has 16 GB of space. Weird how some just don't work when others work perfectly fine. Maybe it's something to do with Dumpling itself?

**Comment by Crementif** [comment]
The latest version should be much better in terms of recognizing USB drives and also supports exfat formatted USB drives now! Lemme know if it doesn't resolve the issue and I'll try to look into it more!
