### ISSUE TITLE
Wii U Wii Virtual Console Games Will Not Appear on Digital Games List.

### ISSUE THREAD

**Issue by SammyD2002** [dumpling-app/dumpling#15]
Hello. I downloaded this tool earlier today to dump my digital copy of Kirby's Return to Dreamland so I could play romhacks on an emulator, but when I entered the Dump Digital Games Menu, it, along with Rhythm Heaven Fever, my only other Wii Virtual Console game didn't appear. I am on version 5.5.4 of the Wii U Menu, with CBHC, and on version 2.1.3 of Dumpling. I have tried rebooting the console and deleting other applications to see if it caused them to appear to no avail. Thank you for taking the time to read this issue.

**Comment by Crementif** [comment]
A very late response, but I was eventually planning to introduce Wii dumping support in a later update. Besides getting it to dump it in it's original state (afaik it requires some extra steps), I'd really like it if I could have it also extract the .iso (optionally) so that you could just use it with Dolphin directly. Hence why it's missing at the moment, if anyone is reading this.

**Comment by YaketyJoe** [comment]
I’d love if this could get implemented too. The only other way is to dump a full NAND and extract from there, or use DumpsterU (which is a Windows program to extract them from a hard drive).

**Comment by mattsxp** [comment]
How did you extract it from the full NAND dump? I used Nand Dumper and dumped all 5 options onto my SD card.

**Comment by Crementif** [comment]
Slightly irrelevant (and sorry that I haven't gotten to find a method to break the security that's around the Wii files, seems more troublesome then I thought), you can also dump your online files and download them through Cemu's Download Manager. It's described in this guide: https://cemu.cfw.guide/dumping-games.html?tab=digital-titles, and after it has installed you should be able to right-click the game in Cemu's game list and open the game directory to be able to see those files. It uses the same eshop functionality that also allows you to make eshop purchases using it, and thus grabs them directly from Nintendo.

**Comment by Crementif** [comment]
With the latest release it's finally possible to dump Wii games (albeit in it's raw format aka .nfs files so you'll have to use nfs2iso2nfs to use them with Dolphin and such)! Glad to finally support it though. If you ever get to use it, feel free to let me know if there's any further problems.

**Comment by Crementif** [comment]
Unfortunately the release had some serious bugs with disc dumping so I've redacted it until I am back from my holidays. Should be out in a week or two though.

**Comment by mattsxp** [comment]
Hey thanks for following up and taking the time to address the issue! No worries, enjoy your holidays!

**Comment by Crementif** [comment]
Just released 2.4.0b which fixed the issues with the redacted release. Lemme know if you stumble upon any issues if you do happen to try it out.

**Comment by mattsxp** [comment]
Working great on my end now! Your work is super appreciated, and I really can't overstate that. Especially with the shop going down within a year. It's people like you that help make game preservation a reality.
