### ISSUE TITLE
Disc Dump Crashes Immediately

### ISSUE THREAD

**Issue by Spider-bomb** [dumpling-app/dumpling#4]
When I select the option to dump a game disc, it immediately freezes the system. I'm on version 2.0.4, just installed Haxchi (not coldboot) the other day. Everything else seems to work fine (While I'm here I should say, it's otherwise a great program, very easy to use and understand.) The disc drive sounds like it's starting up as soon as the game freezes, before stopping a few seconds later. If there's any other information to provide or something else that might solve this problem, please let me know.

**Comment by CJK95** [comment]
Did you launch Mocha CFW before dumpling?

**Comment by Spider-bomb** [comment]
No, I only have Haxchi. Is Mocha necessary? Everything else seems to work just fine.

**Comment by CJK95** [comment]
> No, I only have Haxchi. Is Mocha necessary? Everything else seems to work just fine.

I always launch MochaCFW immediately prior to launching dumpling - which means I enter homebrew via the browser when I want to use dumlping (which automatically enters after about 5 seconds, no internet needed).   The GBA forums where dumpling was originally announced mention some other methods that may work

**Comment by Crementif** [comment]
Sorry for the late response!

Unfortunately Dumpling's disc dumping option doesn't work well with Coldboot Haxchi at the moment :/

I've been working on a massive fix for a ton of issues in the next update, but it's been incredibly difficult to get working unfortunately. It will also fix this issue.

**Comment by Crementif** [comment]
It should be fixed in the new update! Feel free to let me know if it helped you (or if it didn't solve your problem), if you happen to use it.
